pipeline {
    agent any
    environment {
        CI = 'true'
    }
    stages {
        stage('Build') { 
            steps {
                sh 'npm run bulid' 
            }
        }
        stage('Test') { 
            steps {
                sh './jenkins/scripts/test.sh' 
            }
        }
        stage('Run') { 
            steps {
                sh 'pm2 start ./ecosystem.config.js --env=production' 
            }
        }
    }
}